/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Due Cards */
        get: operations["get_due_cards_study_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Cards */
        get: operations["get_practice_cards_study_practice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Card */
        post: operations["review_card_study_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study/evaluate-answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Answer */
        post: operations["evaluate_answer_study_evaluate_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Summary */
        get: operations["get_dashboard_summary_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exams */
        get: operations["list_exams_exams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exam History */
        get: operations["list_exam_history_exam_sessions_get"];
        put?: never;
        /** Start Exam Session */
        post: operations["start_exam_session_exam_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam Session */
        get: operations["get_exam_session_exam_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{session_id}/answers/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Exam Answer */
        put: operations["save_exam_answer_exam_sessions__session_id__answers__card_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{session_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Exam Session */
        post: operations["submit_exam_session_exam_sessions__session_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{session_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exam Result */
        get: operations["get_exam_result_exam_sessions__session_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation-exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Navigation Exams */
        get: operations["list_navigation_exams_navigation_exams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Navigation History */
        get: operations["list_navigation_history_navigation_sessions_get"];
        put?: never;
        /** Start Navigation Session */
        post: operations["start_navigation_session_navigation_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigation Session */
        get: operations["get_navigation_session_navigation_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation-sessions/{session_id}/answers/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Navigation Answer */
        put: operations["save_navigation_answer_navigation_sessions__session_id__answers__task_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation-sessions/{session_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Navigation Session */
        post: operations["submit_navigation_session_navigation_sessions__session_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation-sessions/{session_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Navigation Result */
        get: operations["get_navigation_result_navigation_sessions__session_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/transcribe-audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe Audio */
        post: operations["transcribe_audio_ai_transcribe_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        /** Update Settings */
        put: operations["update_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioTranscriptionOut */
        AudioTranscriptionOut: {
            /** Transcript */
            transcript: string;
        };
        /** Body_transcribe_audio_ai_transcribe_audio_post */
        Body_transcribe_audio_ai_transcribe_audio_post: {
            /**
             * Audio
             * Format: binary
             */
            audio: string;
            /**
             * Language
             * @default de
             */
            language: string;
        };
        /** CardContentOut */
        CardContentOut: {
            /** Text */
            text: string;
            /** Images */
            images: components["schemas"]["CardImageOut"][];
        };
        /** CardImageOut */
        CardImageOut: {
            /** Image Id */
            image_id: string;
            /** Storage Key */
            storage_key: string;
            /** Alt Text */
            alt_text?: string | null;
        };
        /** DashboardSummaryOut */
        DashboardSummaryOut: {
            /** Due Now */
            due_now: number;
            /** Reviewed Today */
            reviewed_today: number;
            /** Streak Days */
            streak_days: number;
            /** Due By Topic */
            due_by_topic: {
                [key: string]: number;
            };
            /** Recommended Topic */
            recommended_topic?: string | null;
            /** Available Cards */
            available_cards: number;
        };
        /** EvaluateAnswerIn */
        EvaluateAnswerIn: {
            /** Card Id */
            card_id: string;
            /** User Answer */
            user_answer: string;
        };
        /** EvaluateAnswerOut */
        EvaluateAnswerOut: {
            /** Card Id */
            card_id: string;
            /** Awarded Points */
            awarded_points: number;
            /** Max Points */
            max_points: number;
            /** Verdict */
            verdict: string;
            /** Reasoning Summary */
            reasoning_summary: string;
            /** Mistakes */
            mistakes: string[];
            /** Missing Points */
            missing_points: string[];
            /** Improved Answer Suggestion */
            improved_answer_suggestion: string;
            /** Suggested Rating */
            suggested_rating: number;
        };
        /** ExamQuestionOut */
        ExamQuestionOut: {
            /** Question Number */
            question_number: number;
            /** Card Id */
            card_id: string;
            /** Question Text */
            question_text: string;
            /** Question Images */
            question_images: components["schemas"]["CardImageOut"][];
            /** Student Answer */
            student_answer: string;
            /** Answered At */
            answered_at?: string | null;
        };
        /** ExamQuestionResultOut */
        ExamQuestionResultOut: {
            /** Question Number */
            question_number: number;
            /** Card Id */
            card_id: string;
            /** Question Text */
            question_text: string;
            /** Reference Short Answer */
            reference_short_answer: string[];
            /** Student Answer */
            student_answer: string;
            /** Score */
            score: number;
            /** Is Correct */
            is_correct: boolean;
            /** Feedback */
            feedback: string;
            /** Errors */
            errors: string[];
        };
        /** ExamResultOut */
        ExamResultOut: {
            /** Session Id */
            session_id: string;
            /** Sheet Number */
            sheet_number: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Submitted At */
            submitted_at?: string | null;
            /** Time Limit Minutes */
            time_limit_minutes: number;
            /** Time Over */
            time_over: boolean;
            /** Total Score */
            total_score: number;
            /** Max Score */
            max_score: number;
            /** Passed */
            passed: boolean;
            /** Pass Score Threshold */
            pass_score_threshold: number;
            /** Questions */
            questions: components["schemas"]["ExamQuestionResultOut"][];
        };
        /** ExamSessionHistoryOut */
        ExamSessionHistoryOut: {
            /** Session Id */
            session_id: string;
            /** Sheet Number */
            sheet_number: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Submitted At */
            submitted_at?: string | null;
            /** Total Score */
            total_score?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Passed */
            passed?: boolean | null;
            /** Time Over */
            time_over: boolean;
        };
        /** ExamSessionOut */
        ExamSessionOut: {
            /** Session Id */
            session_id: string;
            /** Sheet Number */
            sheet_number: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Submitted At */
            submitted_at?: string | null;
            /** Deadline At */
            deadline_at: string;
            /** Time Limit Minutes */
            time_limit_minutes: number;
            /** Time Remaining Seconds */
            time_remaining_seconds: number;
            /** Time Over */
            time_over: boolean;
            /** Question Count */
            question_count: number;
            /** Questions */
            questions: components["schemas"]["ExamQuestionOut"][];
        };
        /** ExamTemplateOut */
        ExamTemplateOut: {
            /** Sheet Number */
            sheet_number: number;
            /** Display Name */
            display_name: string;
            /** Question Count */
            question_count: number;
            /** Time Limit Minutes */
            time_limit_minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NavigationQuestionOut */
        NavigationQuestionOut: {
            /** Task Number */
            task_number: number;
            /** Task Id */
            task_id: string;
            /** Points */
            points: number;
            /** Context */
            context: string;
            /** Sub Questions */
            sub_questions: components["schemas"]["SubQuestionOut"][];
            /** Student Answer */
            student_answer: string;
            /** Answered At */
            answered_at?: string | null;
        };
        /** NavigationQuestionResultOut */
        NavigationQuestionResultOut: {
            /** Task Number */
            task_number: number;
            /** Task Id */
            task_id: string;
            /** Context */
            context: string;
            /** Sub Questions */
            sub_questions: string[];
            /** Key Answers */
            key_answers: string[];
            /** Solution Text */
            solution_text: string;
            /** Student Answer */
            student_answer: string;
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
            /** Is Correct */
            is_correct: boolean;
            /** Feedback */
            feedback: string;
        };
        /** NavigationResultOut */
        NavigationResultOut: {
            /** Session Id */
            session_id: string;
            /** Sheet Number */
            sheet_number: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Submitted At */
            submitted_at?: string | null;
            /** Time Limit Minutes */
            time_limit_minutes: number;
            /** Time Over */
            time_over: boolean;
            /** Total Score */
            total_score: number;
            /** Max Score */
            max_score: number;
            /** Passed */
            passed: boolean;
            /** Pass Score Threshold */
            pass_score_threshold: number;
            /** Questions */
            questions: components["schemas"]["NavigationQuestionResultOut"][];
        };
        /** NavigationSessionHistoryOut */
        NavigationSessionHistoryOut: {
            /** Session Id */
            session_id: string;
            /** Sheet Number */
            sheet_number: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Submitted At */
            submitted_at?: string | null;
            /** Total Score */
            total_score?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Passed */
            passed?: boolean | null;
            /** Time Over */
            time_over: boolean;
        };
        /** NavigationSessionOut */
        NavigationSessionOut: {
            /** Session Id */
            session_id: string;
            /** Sheet Number */
            sheet_number: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Submitted At */
            submitted_at?: string | null;
            /** Deadline At */
            deadline_at: string;
            /** Time Limit Minutes */
            time_limit_minutes: number;
            /** Time Remaining Seconds */
            time_remaining_seconds: number;
            /** Time Over */
            time_over: boolean;
            /** Task Count */
            task_count: number;
            /** Questions */
            questions: components["schemas"]["NavigationQuestionOut"][];
        };
        /** NavigationTemplateOut */
        NavigationTemplateOut: {
            /** Sheet Number */
            sheet_number: number;
            /** Display Name */
            display_name: string;
            /** Task Count */
            task_count: number;
            /** Total Points */
            total_points: number;
            /** Time Limit Minutes */
            time_limit_minutes: number;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Card Id */
            card_id: string;
            /** Rating */
            rating: number;
        };
        /** SaveAnswerIn */
        SaveAnswerIn: {
            /**
             * Student Answer
             * @default
             */
            student_answer: string;
        };
        /** SaveAnswerOut */
        SaveAnswerOut: {
            /** Session Id */
            session_id: string;
            /** Card Id */
            card_id: string;
            /** Question Number */
            question_number: number;
            /** Student Answer */
            student_answer: string;
            /** Answered At */
            answered_at?: string | null;
        };
        /** SaveNavigationAnswerIn */
        SaveNavigationAnswerIn: {
            /**
             * Student Answer
             * @default
             */
            student_answer: string;
        };
        /** SaveNavigationAnswerOut */
        SaveNavigationAnswerOut: {
            /** Session Id */
            session_id: string;
            /** Task Id */
            task_id: string;
            /** Task Number */
            task_number: number;
            /** Student Answer */
            student_answer: string;
            /** Answered At */
            answered_at?: string | null;
        };
        /** SchedulingInfoOut */
        SchedulingInfoOut: {
            /** State */
            state: string;
            /** Stability */
            stability: number;
            /** Difficulty */
            difficulty: number;
            /** Reps */
            reps: number;
            /** Lapses */
            lapses: number;
            /** Due */
            due: string;
            /** Last Review */
            last_review?: string | null;
        };
        /**
         * SettingsIn
         * @description Request body for `PUT /settings`.
         *
         *     `openai_api_key` semantics: omit to leave unchanged; pass `null` or `""`
         *     to clear the stored key; pass a string to replace it.
         */
        SettingsIn: {
            /** Ai Enabled */
            ai_enabled?: boolean | null;
            /** Openai Api Key */
            openai_api_key?: string | null;
            /** Openai Chat Model */
            openai_chat_model?: string | null;
            /** Openai Transcription Model */
            openai_transcription_model?: string | null;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Ai Enabled */
            ai_enabled: boolean;
            /** Openai Api Key Set */
            openai_api_key_set: boolean;
            /** Openai Chat Model */
            openai_chat_model: string;
            /** Openai Transcription Model */
            openai_transcription_model: string;
        };
        /** StartExamSessionIn */
        StartExamSessionIn: {
            /** Sheet Number */
            sheet_number: number;
            /** Time Limit Minutes */
            time_limit_minutes?: number | null;
        };
        /** StartNavigationSessionIn */
        StartNavigationSessionIn: {
            /** Sheet Number */
            sheet_number: number;
            /** Time Limit Minutes */
            time_limit_minutes?: number | null;
        };
        /** StudyCardOut */
        StudyCardOut: {
            card: components["schemas"]["study__controller__study_controller__CardOut"];
            scheduling_info: components["schemas"]["SchedulingInfoOut"];
        };
        /** SubQuestionOut */
        SubQuestionOut: {
            /** Text */
            text: string;
            /** Points */
            points: number;
        };
        /** TopicOut */
        TopicOut: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** CardOut */
        card__controller__card_controller__CardOut: {
            /** Card Id */
            card_id: string;
            front: components["schemas"]["CardContentOut"];
            answer: components["schemas"]["CardContentOut"];
            /** Short Answer */
            short_answer: string[];
            /** Tags */
            tags: string[];
            /** Exam Sheets */
            exam_sheets: number[];
        };
        /** CardOut */
        study__controller__study_controller__CardOut: {
            /** Card Id */
            card_id: string;
            front: components["schemas"]["CardContentOut"];
            answer: components["schemas"]["CardContentOut"];
            /** Short Answer */
            short_answer: string[];
            /** Tags */
            tags: string[];
            /** Exam Sheets */
            exam_sheets: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_topics_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicOut"][];
                };
            };
        };
    };
    get_due_cards_study_due_get: {
        parameters: {
            query?: {
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyCardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_cards_study_practice_get: {
        parameters: {
            query?: {
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyCardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_card_study_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyCardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_answer_study_evaluate_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_summary_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryOut"];
                };
            };
        };
    };
    get_card_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["card__controller__card_controller__CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exams_exams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTemplateOut"][];
                };
            };
        };
    };
    list_exam_history_exam_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamSessionHistoryOut"][];
                };
            };
        };
    };
    start_exam_session_exam_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExamSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_session_exam_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_exam_answer_exam_sessions__session_id__answers__card_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_exam_session_exam_sessions__session_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_result_exam_sessions__session_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_navigation_exams_navigation_exams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationTemplateOut"][];
                };
            };
        };
    };
    list_navigation_history_navigation_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationSessionHistoryOut"][];
                };
            };
        };
    };
    start_navigation_session_navigation_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartNavigationSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigation_session_navigation_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_navigation_answer_navigation_sessions__session_id__answers__task_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveNavigationAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveNavigationAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_navigation_session_navigation_sessions__session_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_navigation_result_navigation_sessions__session_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_audio_ai_transcribe_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_transcribe_audio_ai_transcribe_audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioTranscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
